/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gametap;


/**
 *
 * @author nhona
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        easy = new javax.swing.JRadioButton();
        medi = new javax.swing.JRadioButton();
        hard = new javax.swing.JRadioButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setBackground(new java.awt.Color(51, 255, 0));
        start.setForeground(new java.awt.Color(255, 0, 0));
        start.setText("BẮT ĐẦU");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, 40));

        jLabel2.setBackground(new java.awt.Color(0, 255, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mức Độ : ");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 70, 30));

        buttonGroup1.add(easy);
        easy.setForeground(new java.awt.Color(255, 255, 255));
        easy.setText("Dễ");
        getContentPane().add(easy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        buttonGroup1.add(medi);
        medi.setForeground(new java.awt.Color(255, 255, 255));
        medi.setText("TB");
        getContentPane().add(medi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        buttonGroup1.add(hard);
        hard.setForeground(new java.awt.Color(255, 255, 255));
        hard.setText("Khó");
        getContentPane().add(hard, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rsz_modau.png"))); // NOI18N
        BG.setText("namdfasf");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
      
        String level = "DỄ";
      
        int speed=200;
        if(easy.isSelected())
            speed = 200;
        if(medi.isSelected()){
            speed = 160;
            level = "TRUNG BÌNH";
        }
   
        if(hard.isSelected()){
            speed = 90;
            level ="KHÓ";
        }
         
        
        JFrame_main game = new JFrame_main(speed,level);
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
 
            }
        });
    }
    
   
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton easy;
    private javax.swing.JRadioButton hard;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton medi;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
